# Artificial Intelligence Practical 3

## 18BCE259: Shrey Viradiya

### AIM: Implement the 8 puzzle problem using DFS

8 puzzle problem is about reaching the final state from any intermediary state. Final State is defined as below:
```
 1 | 2 | 3 
-----------
 4 | 5 | 6 
-----------
 7 | 8 |   
 ```

In [1]:
import numpy as np

In [2]:
class Node:
    def __init__(self, data, parent, act, depth = 0):
        self.data = data
        self.parent = parent
        self.act = act
        self.depth = depth

    def __str__(self):
        return self.data.__repr__() 

In [3]:
initial_node = Node(np.array([[1,2,3],[4,0,6],[7,5,8]]), None, None, 0)

In [4]:
def whereEmpty(node):
    return np.argwhere(node.data == 0)[0]

whereEmpty(initial_node)

array([1, 1])

In [5]:
print(initial_node)

array([[1, 2, 3],
       [4, 0, 6],
       [7, 5, 8]])


In [6]:
def canMoveLeft(node):
    return whereEmpty(node)[1] != 0

def moveLeft(node):
    pointer = whereEmpty(node)
    new_Node = Node(np.copy(node.data), node, 'left', node.depth + 1)    

    temp = new_Node.data[pointer[0], pointer[1] - 1]
    new_Node.data[pointer[0], pointer[1] - 1] = new_Node.data[pointer[0], pointer[1]]
    new_Node.data[pointer[0], pointer[1]] = temp
    
    return new_Node

print(canMoveLeft(initial_node))
print(moveLeft(initial_node))

True
array([[1, 2, 3],
       [0, 4, 6],
       [7, 5, 8]])


In [7]:
def canMoveRight(node):
    return whereEmpty(node)[1] != 2

def moveRight(node):
    pointer = whereEmpty(node)
    new_Node = Node(np.copy(node.data), node, 'right', node.depth + 1)
    
    temp = new_Node.data[pointer[0], pointer[1] + 1]
    new_Node.data[pointer[0], pointer[1] + 1] = new_Node.data[pointer[0], pointer[1]]
    new_Node.data[pointer[0], pointer[1]] = temp
    
    return new_Node

print(canMoveRight(initial_node))
print(moveRight(initial_node))

True
array([[1, 2, 3],
       [4, 6, 0],
       [7, 5, 8]])


In [8]:
def canMoveUp(node):
    return whereEmpty(node)[0] != 0

def moveUp(node):
    pointer = whereEmpty(node)
    
    new_Node = Node(np.copy(node.data), node, 'up', node.depth + 1)
    

    temp = new_Node.data[pointer[0] - 1, pointer[1]]
    new_Node.data[pointer[0] - 1, pointer[1]] = new_Node.data[pointer[0], pointer[1]]
    new_Node.data[pointer[0], pointer[1]] = temp
    
    return new_Node

print(canMoveUp(initial_node))
print(moveUp(initial_node))

True
array([[1, 0, 3],
       [4, 2, 6],
       [7, 5, 8]])


In [9]:
def canMoveDown(node):
    return whereEmpty(node)[0] != 2

def moveDown(node):
    pointer = whereEmpty(node)
    new_Node = Node(np.copy(node.data), node, 'down', node.depth + 1)

    temp = new_Node.data[pointer[0] + 1, pointer[1]]
    new_Node.data[pointer[0] + 1, pointer[1]] = new_Node.data[pointer[0], pointer[1]]
    new_Node.data[pointer[0], pointer[1]] = temp
    
    return new_Node

print(canMoveDown(initial_node))
print(moveDown(initial_node))

True
array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 8]])


In [10]:
def CheckIfFinal(node):
    return np.all(node.data == np.array([[1,2,3],[4,5,6],[7,8,0]]))

CheckIfFinal(initial_node)

False

In [11]:
# Python3 program to check if a given
# instance of 8 puzzle is solvable or not
 
# A utility function to count
# inversions in given array 'arr[]'

def getInvCount(arr):
    inv_count = 0
    empty_value = -1
    for i in range(0, 9):
        for j in range(i + 1, 9):
            if arr[j] != empty_value and arr[i] != empty_value and arr[i] > arr[j]:
                inv_count += 1
    return inv_count
 
     
# This function returns true
# if given 8 puzzle is solvable.
def isSolvable(puzzle) :
 
    # Count inversions in given 8 puzzle
    inv_count = getInvCount([j for sub in puzzle for j in sub])
 
    # return true if inversion count is even.
    return (inv_count % 2 == 0)
     
    # Driver code
puzzle = [[4, 1, 0], [7, 2, 3], [5, 8, 6]]
if(isSolvable(puzzle)) :
    print("Solvable")
else :
    print("Not Solvable")

Solvable


In [12]:
import random

def generatePuzzle(dep = 10):
    node = Node(np.array([[1,2,3],[4,5,6],[7,8,0]]), None, None)

    while (node.depth != 10):
        step = random.randint(1,4)

        if step == 1 and canMoveLeft(node) and node.act != "right":
            node = moveLeft(node)
        elif step == 2 and canMoveRight(node) and node.act != "left":
            node = moveRight(node)
        elif step == 3 and canMoveUp(node) and node.act != "down":
            node = moveUp(node)
        elif step == 4 and canMoveDown(node) and node.act != "up":
            node = moveDown(node)
        else:
            continue
        print(node)

generatePuzzle(8)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 8]])
array([[1, 2, 3],
       [4, 0, 6],
       [7, 5, 8]])
array([[1, 2, 3],
       [0, 4, 6],
       [7, 5, 8]])
array([[1, 2, 3],
       [7, 4, 6],
       [0, 5, 8]])
array([[1, 2, 3],
       [7, 4, 6],
       [5, 0, 8]])
array([[1, 2, 3],
       [7, 4, 6],
       [5, 8, 0]])
array([[1, 2, 3],
       [7, 4, 0],
       [5, 8, 6]])
array([[1, 2, 0],
       [7, 4, 3],
       [5, 8, 6]])
array([[1, 0, 2],
       [7, 4, 3],
       [5, 8, 6]])
array([[1, 4, 2],
       [7, 0, 3],
       [5, 8, 6]])


In [13]:
def DFS(initial_node, max_depth = 10):

    if(not isSolvable(initial_node.data)):
        print("Puzzle Not Solvable")
        return
        
    passed_node = []
    Stack = [initial_node]

    node = None

    while True:
        node = Stack.pop()

        if(CheckIfFinal(node)):
            print("Final State Obtained")
            break

        if(node.depth == max_depth):
            continue
        
        if canMoveLeft(node) and node.act != "right":
            Stack.append(moveLeft(node))
        if canMoveRight(node) and node.act != "left":
            Stack.append(moveRight(node))
        if canMoveUp(node) and node.act != "down":
            Stack.append(moveUp(node))
        if canMoveDown(node) and node.act != "up":
            Stack.append(moveDown(node))

    moves = []
    while (node != None):
        moves.insert(0, node.act)
        node = node.parent

    print("Solution: ")
    print("===========================")
    print("Initial Node: ")

    node = initial_node
    for move in moves:
        print(move)
        if move == 'left':
            node = moveLeft(node)
        elif move == 'right':
            node = moveRight(node)
        elif move == 'up':
            node = moveUp(node)
        elif move == 'down':
            node = moveDown(node)
        print(node)

In [14]:
DFS(initial_node)

Final State Obtained
Solution: 
Initial Node: 
None
array([[1, 2, 3],
       [4, 0, 6],
       [7, 5, 8]])
down
array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 8]])
right
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])


In [15]:
initial_node = Node(np.array([[0,1,3],[4,2,6],[7,5,8]]), None, None)
DFS(initial_node)

Final State Obtained
Solution: 
Initial Node: 
None
array([[0, 1, 3],
       [4, 2, 6],
       [7, 5, 8]])
right
array([[1, 0, 3],
       [4, 2, 6],
       [7, 5, 8]])
down
array([[1, 2, 3],
       [4, 0, 6],
       [7, 5, 8]])
down
array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 8]])
right
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])


In [16]:
initial_node = Node(np.array([[4, 3, 6], [2, 0, 1], [7, 5, 8]]), None, None, 0)
DFS(initial_node, 15)

Final State Obtained
Solution: 
Initial Node: 
None
array([[4, 3, 6],
       [2, 0, 1],
       [7, 5, 8]])
up
array([[4, 0, 6],
       [2, 3, 1],
       [7, 5, 8]])
right
array([[4, 6, 0],
       [2, 3, 1],
       [7, 5, 8]])
down
array([[4, 6, 1],
       [2, 3, 0],
       [7, 5, 8]])
left
array([[4, 6, 1],
       [2, 0, 3],
       [7, 5, 8]])
up
array([[4, 0, 1],
       [2, 6, 3],
       [7, 5, 8]])
right
array([[4, 1, 0],
       [2, 6, 3],
       [7, 5, 8]])
down
array([[4, 1, 3],
       [2, 6, 0],
       [7, 5, 8]])
left
array([[4, 1, 3],
       [2, 0, 6],
       [7, 5, 8]])
left
array([[4, 1, 3],
       [0, 2, 6],
       [7, 5, 8]])
up
array([[0, 1, 3],
       [4, 2, 6],
       [7, 5, 8]])
right
array([[1, 0, 3],
       [4, 2, 6],
       [7, 5, 8]])
down
array([[1, 2, 3],
       [4, 0, 6],
       [7, 5, 8]])
down
array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 8]])
right
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])


In [17]:
initial_node = Node(np.array([[1,2,3],[4,0,5],[7,6,8]]), None, None, 0)
DFS(initial_node, 40)

Puzzle Not Solvable


In [ ]:
initial_node = Node(np.array([[1,2,3],[4,6,5],[7,0,8]]), None, None, 0)
DFS(initial_node, 50)